# startship

# prompt
add_newline = true
format = "$all"
scan_timeout = 10

[aws]
disabled = true
format = '[$symbol$profile(\($region\))]($style) '
symbol = 'aws:'

[battery]
disabled = true

[character]
disabled = false
error_symbol = '[\$](bold red)'
success_symbol = '[\$](bold green)'
use_symbol_for_status = true
vicmd_symbol = '[\$](bold green)'

[cmd_duration]
disabled = false
format = '[$duration]($style) '
min_time = 500
show_milliseconds = true
style = ''

[directory]
disabled = false
format = '[$path]($style)[$read_only]($read_only_style) '
style = 'bold cyan'
truncate_to_repo = true
truncation_length = 0
truncation_symbol = ''

[env_var]
disabled = true
variable = "SHELL"
format = '[$env_value]($style) '

[git_branch]
format = '[$symbol$branch]($style) '
style = 'bold purple'

[git_commit]
disabled = false
only_detached = false
tag_disabled = false
tag_symbol = ''
style = 'bold dimmed green'

[git_status]
style = 'bold red'

[hostname]
disabled = false
format = '[$hostname]($style) '
ssh_only = false
style = 'bold white'
trim_at = '.'

[jobs]
disabled = false
format = '[$symbol$number]($style)'
style = 'bold blue'
symbol = '+'
threshold = 1

[line_break]
disabled = false

[memory_usage]
disabled = true

[perl]
disabled = false
format = '[$symbol($version )]($style) '
style = 'bold dimmed red'
symbol = 'pl:'

[python]
disabled = false
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style) '
pyenv_prefix = ''
pyenv_version_name = false
style = 'bold dimmed red'
symbol = 'py:'

[ruby]
disabled = false
format = '[$symbol($version )]($style) '
style = 'bold dimmed red'
symbol = 'rb:'

[status]
disabled = false
format = '[\[$int $common_meaning$signal_name\]]($style) '

[terraform]
format = '[$symbol$workspace]($style) '
symbol = 'tf:'

[time]
disabled = false
format = '[$time]($style) '
style = 'bold dimmed green'
time_format = '[%Y%m%d.%H%M%S]'

[username]
disabled = false
format = '[$user]($style) '
show_always = true
style_root = 'bold red'
style_user = 'bold green'
